general:
  focus_follows_cursor: true
  toggle_workspace_on_refocus: false

  # How windows should be hidden when switching workspaces.
  # - 'cloak': Recommended. Hides windows with no animation.
  # - 'hide': Legacy method (v3.5 and earlier) that has a brief animation,
  # but has stability issues with some apps.
  hide_method: "cloak"

  # Affects which windows get shown in the native Windows taskbar. Has no
  # effect if `hide_method: 'hide'`.
  # - 'true': Show all windows (regardless of workspace).
  # - 'false': Only show windows from the currently shown workspaces.
  show_all_in_taskbar: false
  cursor_jump:
    enabled: true
    trigger: "window_focus" # Or 'monitor_focus'

gaps:
  scale_with_dpi: true

  inner_gap: "7px"

  outer_gap:
    top: "7px"
    right: "9px"
    bottom: "7px"
    left: "9px"

window_effects:
  focused_window:
    border:
      enabled: false
      color: "#b7c2e9"

    # Remove the title bar from the window's frame. Note that this can
    # cause rendering issues for some applications.
    hide_title_bar:
      enabled: false

    corner_style:
      enabled: false
      # Allowed values: 'square', 'rounded', 'small_rounded'.
      style: "rounded"

    # Change the transparency of the window.
    transparency:
      enabled: false
      # Can be something like '95%' or '0.95' for slightly transparent windows.
      # '0' or '0%' is fully transparent (and, by consequence, unfocusable).
      opacity: "100%"

  other_windows:
    border:
      enabled: false
      color: "#ffffff"
    hide_title_bar:
      enabled: false
    corner_style:
      enabled: false
      style: "rounded"
    transparency:
      enabled: false
      opacity: "100%"

window_behavior:
  initial_state: "tiling"

  state_defaults:
    floating:
      # Whether to center floating windows by default.
      centered: true

      # Whether to show floating windows as always on top.
      shown_on_top: true

    fullscreen:
      # Maximize the window if possible. If the window doesn't have a
      # maximize button, then it'll be fullscreen'ed normally instead.
      maximized: false

      # Whether to show fullscreen windows as always on top.
      shown_on_top: false

workspaces:
  - name: "1"
    display_name: "Swing"
    bind_to_monitor: 0
  - name: "2"
    display_name: "Weave"
    bind_to_monitor: 1
  - name: "3"
    display_name: "Node"
    bind_to_monitor: 1
  - name: "4"
    display_name: "Beats"
    bind_to_monitor: 0
  - name: "5"
    display_name: "Void"
    bind_to_monitor: 0

window_rules:
  - commands: ["ignore"]
    match:
      # Ignores picture-in-picture windows for browsers.
      - window_title: { regex: "[Pp]icture.in.[Pp]icture" }
        window_class: { regex: "Chrome_WidgetWin_1|MozillaDialogClass" }

      # Ignore rules for various 3rd-party apps.
      - window_process: { equals: "PowerToys" }
        window_class: { regex: 'HwndWrapper\[PowerToys\.PowerAccent.*?\]' }
      - window_process: { equals: "PowerToys" }
        window_title: { regex: ".*? - Peek" }
      - window_process: { equals: "Lively" }
        window_class: { regex: "HwndWrapper" }
      - window_process: { equals: "EXCEL" }
        window_class: { not_regex: "XLMAIN" }
      - window_process: { equals: "WINWORD" }
        window_class: { not_regex: "OpusApp" }
      - window_process: { equals: "POWERPNT" }
        window_class: { not_regex: "PPTFrameClass" }

keybindings:
  # Shift focus in a given direction.
  - commands: ["focus --direction left"]
    bindings: ["alt+h"]
  - commands: ["focus --direction right"]
    bindings: ["alt+l"]

  # Move focused window in a given direction.
  - commands: ["move --direction left"]
    bindings: ["alt+shift+h"]
  - commands: ["move --direction right"]
    bindings: ["alt+shift+l"]

  # Resize focused window by a percentage or pixel amount.
  - commands: ["resize --width -2%"]
    bindings: ["alt+j"]
  - commands: ["resize --width +2%"]
    bindings: ["alt+k"]

  # Disables window management and all other keybindings until alt+shift+p
  # is pressed again.
  - commands: ["wm-toggle-pause"]
    bindings: ["alt+shift+p"]

    # Re-evaluate configuration file.
  - commands: ["wm-reload-config"]
    bindings: ["alt+shift+r"]

  # Minimize focused window.
  - commands: ["toggle-minimized"]
    bindings: ["alt+m"]

  # Close focused window.
  - commands: ["close"]
    bindings: ["alt+c"]

  # Change the focused window to be floating.
  - commands: ["toggle-floating --centered"]
    bindings: ["alt+f"]

  # Change the focused window to be tiling.
  - commands: ["toggle-tiling"]
    bindings: ["alt+t"]

  # Change focus to a workspace defined in `workspaces` config.
  - commands: ["focus --workspace 1"]
    bindings: ["alt+1"]
  - commands: ["focus --workspace 2"]
    bindings: ["alt+2"]
  - commands: ["focus --workspace 3"]
    bindings: ["alt+3"]
  - commands: ["focus --workspace 4"]
    bindings: ["alt+4"]
  - commands: ["focus --workspace 5"]
    bindings: ["alt+5"]

    # Move the focused window's parent workspace to a monitor in a given
    # direction.
  - commands: ["move-workspace --direction left"]
    bindings: ["alt+shift+a"]
  - commands: ["move-workspace --direction right"]
    bindings: ["alt+shift+f"]

    # Move focused window to a workspace defined in `workspaces` config.
  - commands: ["move --workspace 1", "focus --workspace 1"]
    bindings: ["alt+shift+1"]
  - commands: ["move --workspace 2", "focus --workspace 2"]
    bindings: ["alt+shift+2"]
  - commands: ["move --workspace 3", "focus --workspace 3"]
    bindings: ["alt+shift+3"]
  - commands: ["move --workspace 4", "focus --workspace 4"]
    bindings: ["alt+shift+4"]
  - commands: ["move --workspace 5", "focus --workspace 5"]
    bindings: ["alt+shift+5"]
